### ISSUE TITLE
博客的意义（深度长文，TL;DR）

### ISSUE THREAD

**Issue by LiuDianshi** [LiuDianshi/LiuDianshi.github.io#1]
这是我的博客，

这个世界有很多类似的博客，但这个**只属于我**，

这是我的生活，

我必须像爱护生命一样爱护我的博客，

没有博客，我的存在就没有任何意义，

没有我，我的博客将没有任何意义。

**Comment by ksco** [comment]
**没有我，我的博客将没有任何意义。**

**Comment by LiuDianshi** [comment]
@ksco 失了志了？

**Comment by LiuDianshi** [comment]
666
